// Code generated by SQLBoiler 4.12.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// MovieGenre is an object representing the database table.
type MovieGenre struct {
	ID      int `boil:"id" json:"id" toml:"id" yaml:"id"`
	MovieID int `boil:"movie_id" json:"movie_id" toml:"movie_id" yaml:"movie_id"`
	GenreID int `boil:"genre_id" json:"genre_id" toml:"genre_id" yaml:"genre_id"`

	R *movieGenreR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L movieGenreL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var MovieGenreColumns = struct {
	ID      string
	MovieID string
	GenreID string
}{
	ID:      "id",
	MovieID: "movie_id",
	GenreID: "genre_id",
}

var MovieGenreTableColumns = struct {
	ID      string
	MovieID string
	GenreID string
}{
	ID:      "movie_genres.id",
	MovieID: "movie_genres.movie_id",
	GenreID: "movie_genres.genre_id",
}

// Generated where

var MovieGenreWhere = struct {
	ID      whereHelperint
	MovieID whereHelperint
	GenreID whereHelperint
}{
	ID:      whereHelperint{field: "\"movie_genres\".\"id\""},
	MovieID: whereHelperint{field: "\"movie_genres\".\"movie_id\""},
	GenreID: whereHelperint{field: "\"movie_genres\".\"genre_id\""},
}

// MovieGenreRels is where relationship names are stored.
var MovieGenreRels = struct {
	Genre string
	Movie string
}{
	Genre: "Genre",
	Movie: "Movie",
}

// movieGenreR is where relationships are stored.
type movieGenreR struct {
	Genre *Genre `boil:"Genre" json:"Genre" toml:"Genre" yaml:"Genre"`
	Movie *Movie `boil:"Movie" json:"Movie" toml:"Movie" yaml:"Movie"`
}

// NewStruct creates a new relationship struct
func (*movieGenreR) NewStruct() *movieGenreR {
	return &movieGenreR{}
}

func (r *movieGenreR) GetGenre() *Genre {
	if r == nil {
		return nil
	}
	return r.Genre
}

func (r *movieGenreR) GetMovie() *Movie {
	if r == nil {
		return nil
	}
	return r.Movie
}

// movieGenreL is where Load methods for each relationship are stored.
type movieGenreL struct{}

var (
	movieGenreAllColumns            = []string{"id", "movie_id", "genre_id"}
	movieGenreColumnsWithoutDefault = []string{}
	movieGenreColumnsWithDefault    = []string{"id", "movie_id", "genre_id"}
	movieGenrePrimaryKeyColumns     = []string{"id"}
	movieGenreGeneratedColumns      = []string{}
)

type (
	// MovieGenreSlice is an alias for a slice of pointers to MovieGenre.
	// This should almost always be used instead of []MovieGenre.
	MovieGenreSlice []*MovieGenre
	// MovieGenreHook is the signature for custom MovieGenre hook methods
	MovieGenreHook func(context.Context, boil.ContextExecutor, *MovieGenre) error

	movieGenreQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	movieGenreType                 = reflect.TypeOf(&MovieGenre{})
	movieGenreMapping              = queries.MakeStructMapping(movieGenreType)
	movieGenrePrimaryKeyMapping, _ = queries.BindMapping(movieGenreType, movieGenreMapping, movieGenrePrimaryKeyColumns)
	movieGenreInsertCacheMut       sync.RWMutex
	movieGenreInsertCache          = make(map[string]insertCache)
	movieGenreUpdateCacheMut       sync.RWMutex
	movieGenreUpdateCache          = make(map[string]updateCache)
	movieGenreUpsertCacheMut       sync.RWMutex
	movieGenreUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var movieGenreAfterSelectHooks []MovieGenreHook

var movieGenreBeforeInsertHooks []MovieGenreHook
var movieGenreAfterInsertHooks []MovieGenreHook

var movieGenreBeforeUpdateHooks []MovieGenreHook
var movieGenreAfterUpdateHooks []MovieGenreHook

var movieGenreBeforeDeleteHooks []MovieGenreHook
var movieGenreAfterDeleteHooks []MovieGenreHook

var movieGenreBeforeUpsertHooks []MovieGenreHook
var movieGenreAfterUpsertHooks []MovieGenreHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *MovieGenre) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range movieGenreAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *MovieGenre) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range movieGenreBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *MovieGenre) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range movieGenreAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *MovieGenre) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range movieGenreBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *MovieGenre) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range movieGenreAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *MovieGenre) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range movieGenreBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *MovieGenre) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range movieGenreAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *MovieGenre) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range movieGenreBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *MovieGenre) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range movieGenreAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddMovieGenreHook registers your hook function for all future operations.
func AddMovieGenreHook(hookPoint boil.HookPoint, movieGenreHook MovieGenreHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		movieGenreAfterSelectHooks = append(movieGenreAfterSelectHooks, movieGenreHook)
	case boil.BeforeInsertHook:
		movieGenreBeforeInsertHooks = append(movieGenreBeforeInsertHooks, movieGenreHook)
	case boil.AfterInsertHook:
		movieGenreAfterInsertHooks = append(movieGenreAfterInsertHooks, movieGenreHook)
	case boil.BeforeUpdateHook:
		movieGenreBeforeUpdateHooks = append(movieGenreBeforeUpdateHooks, movieGenreHook)
	case boil.AfterUpdateHook:
		movieGenreAfterUpdateHooks = append(movieGenreAfterUpdateHooks, movieGenreHook)
	case boil.BeforeDeleteHook:
		movieGenreBeforeDeleteHooks = append(movieGenreBeforeDeleteHooks, movieGenreHook)
	case boil.AfterDeleteHook:
		movieGenreAfterDeleteHooks = append(movieGenreAfterDeleteHooks, movieGenreHook)
	case boil.BeforeUpsertHook:
		movieGenreBeforeUpsertHooks = append(movieGenreBeforeUpsertHooks, movieGenreHook)
	case boil.AfterUpsertHook:
		movieGenreAfterUpsertHooks = append(movieGenreAfterUpsertHooks, movieGenreHook)
	}
}

// One returns a single movieGenre record from the query.
func (q movieGenreQuery) One(ctx context.Context, exec boil.ContextExecutor) (*MovieGenre, error) {
	o := &MovieGenre{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for movie_genres")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all MovieGenre records from the query.
func (q movieGenreQuery) All(ctx context.Context, exec boil.ContextExecutor) (MovieGenreSlice, error) {
	var o []*MovieGenre

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to MovieGenre slice")
	}

	if len(movieGenreAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all MovieGenre records in the query.
func (q movieGenreQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count movie_genres rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q movieGenreQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if movie_genres exists")
	}

	return count > 0, nil
}

// Genre pointed to by the foreign key.
func (o *MovieGenre) Genre(mods ...qm.QueryMod) genreQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.GenreID),
	}

	queryMods = append(queryMods, mods...)

	return Genres(queryMods...)
}

// Movie pointed to by the foreign key.
func (o *MovieGenre) Movie(mods ...qm.QueryMod) movieQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.MovieID),
	}

	queryMods = append(queryMods, mods...)

	return Movies(queryMods...)
}

// LoadGenre allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (movieGenreL) LoadGenre(ctx context.Context, e boil.ContextExecutor, singular bool, maybeMovieGenre interface{}, mods queries.Applicator) error {
	var slice []*MovieGenre
	var object *MovieGenre

	if singular {
		var ok bool
		object, ok = maybeMovieGenre.(*MovieGenre)
		if !ok {
			object = new(MovieGenre)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeMovieGenre)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeMovieGenre))
			}
		}
	} else {
		s, ok := maybeMovieGenre.(*[]*MovieGenre)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeMovieGenre)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeMovieGenre))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &movieGenreR{}
		}
		args = append(args, object.GenreID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &movieGenreR{}
			}

			for _, a := range args {
				if a == obj.GenreID {
					continue Outer
				}
			}

			args = append(args, obj.GenreID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`genres`),
		qm.WhereIn(`genres.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Genre")
	}

	var resultSlice []*Genre
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Genre")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for genres")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for genres")
	}

	if len(movieGenreAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Genre = foreign
		if foreign.R == nil {
			foreign.R = &genreR{}
		}
		foreign.R.MovieGenres = append(foreign.R.MovieGenres, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.GenreID == foreign.ID {
				local.R.Genre = foreign
				if foreign.R == nil {
					foreign.R = &genreR{}
				}
				foreign.R.MovieGenres = append(foreign.R.MovieGenres, local)
				break
			}
		}
	}

	return nil
}

// LoadMovie allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (movieGenreL) LoadMovie(ctx context.Context, e boil.ContextExecutor, singular bool, maybeMovieGenre interface{}, mods queries.Applicator) error {
	var slice []*MovieGenre
	var object *MovieGenre

	if singular {
		var ok bool
		object, ok = maybeMovieGenre.(*MovieGenre)
		if !ok {
			object = new(MovieGenre)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeMovieGenre)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeMovieGenre))
			}
		}
	} else {
		s, ok := maybeMovieGenre.(*[]*MovieGenre)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeMovieGenre)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeMovieGenre))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &movieGenreR{}
		}
		args = append(args, object.MovieID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &movieGenreR{}
			}

			for _, a := range args {
				if a == obj.MovieID {
					continue Outer
				}
			}

			args = append(args, obj.MovieID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`movies`),
		qm.WhereIn(`movies.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Movie")
	}

	var resultSlice []*Movie
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Movie")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for movies")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for movies")
	}

	if len(movieGenreAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Movie = foreign
		if foreign.R == nil {
			foreign.R = &movieR{}
		}
		foreign.R.MovieGenres = append(foreign.R.MovieGenres, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.MovieID == foreign.ID {
				local.R.Movie = foreign
				if foreign.R == nil {
					foreign.R = &movieR{}
				}
				foreign.R.MovieGenres = append(foreign.R.MovieGenres, local)
				break
			}
		}
	}

	return nil
}

// SetGenre of the movieGenre to the related item.
// Sets o.R.Genre to related.
// Adds o to related.R.MovieGenres.
func (o *MovieGenre) SetGenre(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Genre) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"movie_genres\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"genre_id"}),
		strmangle.WhereClause("\"", "\"", 2, movieGenrePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.GenreID = related.ID
	if o.R == nil {
		o.R = &movieGenreR{
			Genre: related,
		}
	} else {
		o.R.Genre = related
	}

	if related.R == nil {
		related.R = &genreR{
			MovieGenres: MovieGenreSlice{o},
		}
	} else {
		related.R.MovieGenres = append(related.R.MovieGenres, o)
	}

	return nil
}

// SetMovie of the movieGenre to the related item.
// Sets o.R.Movie to related.
// Adds o to related.R.MovieGenres.
func (o *MovieGenre) SetMovie(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Movie) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"movie_genres\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"movie_id"}),
		strmangle.WhereClause("\"", "\"", 2, movieGenrePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.MovieID = related.ID
	if o.R == nil {
		o.R = &movieGenreR{
			Movie: related,
		}
	} else {
		o.R.Movie = related
	}

	if related.R == nil {
		related.R = &movieR{
			MovieGenres: MovieGenreSlice{o},
		}
	} else {
		related.R.MovieGenres = append(related.R.MovieGenres, o)
	}

	return nil
}

// MovieGenres retrieves all the records using an executor.
func MovieGenres(mods ...qm.QueryMod) movieGenreQuery {
	mods = append(mods, qm.From("\"movie_genres\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"movie_genres\".*"})
	}

	return movieGenreQuery{q}
}

// FindMovieGenre retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindMovieGenre(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*MovieGenre, error) {
	movieGenreObj := &MovieGenre{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"movie_genres\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, movieGenreObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from movie_genres")
	}

	if err = movieGenreObj.doAfterSelectHooks(ctx, exec); err != nil {
		return movieGenreObj, err
	}

	return movieGenreObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *MovieGenre) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no movie_genres provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(movieGenreColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	movieGenreInsertCacheMut.RLock()
	cache, cached := movieGenreInsertCache[key]
	movieGenreInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			movieGenreAllColumns,
			movieGenreColumnsWithDefault,
			movieGenreColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(movieGenreType, movieGenreMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(movieGenreType, movieGenreMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"movie_genres\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"movie_genres\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into movie_genres")
	}

	if !cached {
		movieGenreInsertCacheMut.Lock()
		movieGenreInsertCache[key] = cache
		movieGenreInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the MovieGenre.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *MovieGenre) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	movieGenreUpdateCacheMut.RLock()
	cache, cached := movieGenreUpdateCache[key]
	movieGenreUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			movieGenreAllColumns,
			movieGenrePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update movie_genres, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"movie_genres\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, movieGenrePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(movieGenreType, movieGenreMapping, append(wl, movieGenrePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update movie_genres row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for movie_genres")
	}

	if !cached {
		movieGenreUpdateCacheMut.Lock()
		movieGenreUpdateCache[key] = cache
		movieGenreUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q movieGenreQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for movie_genres")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for movie_genres")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o MovieGenreSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), movieGenrePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"movie_genres\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, movieGenrePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in movieGenre slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all movieGenre")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *MovieGenre) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no movie_genres provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(movieGenreColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	movieGenreUpsertCacheMut.RLock()
	cache, cached := movieGenreUpsertCache[key]
	movieGenreUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			movieGenreAllColumns,
			movieGenreColumnsWithDefault,
			movieGenreColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			movieGenreAllColumns,
			movieGenrePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert movie_genres, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(movieGenrePrimaryKeyColumns))
			copy(conflict, movieGenrePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"movie_genres\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(movieGenreType, movieGenreMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(movieGenreType, movieGenreMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert movie_genres")
	}

	if !cached {
		movieGenreUpsertCacheMut.Lock()
		movieGenreUpsertCache[key] = cache
		movieGenreUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single MovieGenre record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *MovieGenre) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no MovieGenre provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), movieGenrePrimaryKeyMapping)
	sql := "DELETE FROM \"movie_genres\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from movie_genres")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for movie_genres")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q movieGenreQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no movieGenreQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from movie_genres")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for movie_genres")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o MovieGenreSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(movieGenreBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), movieGenrePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"movie_genres\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, movieGenrePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from movieGenre slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for movie_genres")
	}

	if len(movieGenreAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *MovieGenre) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindMovieGenre(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MovieGenreSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := MovieGenreSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), movieGenrePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"movie_genres\".* FROM \"movie_genres\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, movieGenrePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in MovieGenreSlice")
	}

	*o = slice

	return nil
}

// MovieGenreExists checks if the MovieGenre row exists.
func MovieGenreExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"movie_genres\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if movie_genres exists")
	}

	return exists, nil
}
